### ISSUE TITLE
Links to parfait pattern?

### ISSUE THREAD

**Issue by wsargent** [dickwall/activator-akka-scala-parfait#1]
Thanks, this looks awesome!

Did a search on Google, this seems to be it (also called cupcake pattern):

http://stackoverflow.com/a/26022355/5266

**Comment by dickwall** [comment]
hmmm - not really the same thing. At least this version of cupcake uses Reader monad and Scalaz, ignoring the implicits (which are the crux of Parfait). Reader also doesn't help with the Akka props problem either, nothing does unless you pass configuration into the props method in some manner - I suppose you could make props return a reader and later pass in the config, but if you can get the compiler to do all this for you. The only thing that seems to be the same is that only config goes into the traits, and the traits subtyping is used :-). The implicit parameters really are the key thing in Parfait - maybe I should have called it icing gun instead ;-).
